# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('phone_number', models.IntegerField()),
                ('country_of_origin', models.CharField(choices=[(b'NGA', b'Nigeria'), (b'GBR', b'United Kingdom'), (b'USA', b'United States')], max_length=3)),
                ('country_of_residence', models.CharField(choices=[(b'NGA', b'Nigeria'), (b'GBR', b'United Kingdom'), (b'USA', b'United States')], max_length=3)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
